default:
  javac cpsc2150/listDec/IShuffleList.java
  javac cpsc2150/listDec/ShuffleApp.java
  javac cpsc2150/listDec/ShuffleList.java

run:
  java cpsc2150/listDec/ShuffleApp.java

clean:
  rm -f cpsc2150/listDec/*.class
